// <auto-generated />
using System;
using MesaSitec.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesaSitec.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(MesaSitecDbContext))]
    [Migration("20260730174905_CrearEsquemaInicial")]
    partial class CrearEsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("MesaSitec.Dominio.Entidades.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SlaHoras")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Activo");

                    b.ToTable("Categorias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categorias_SlaHoras_Positivo", "\"SlaHoras\" > 0");
                        });
                });

            modelBuilder.Entity("MesaSitec.Dominio.Entidades.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaLimiteSla")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoResolucion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SolicitanteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "AgenteId");

                    b.HasIndex("TenantId", "CategoriaId");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.HasIndex("TenantId", "Estado");

                    b.HasIndex("TenantId", "FechaCreacion");

                    b.HasIndex("TenantId", "Prioridad");

                    b.HasIndex("TenantId", "SolicitanteId");

                    b.ToTable("Solicitudes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Solicitudes_Descripcion_Longitud", "length(trim(\"Descripcion\")) BETWEEN 10 AND 4000");

                            t.HasCheckConstraint("CK_Solicitudes_Titulo_Longitud", "length(trim(\"Titulo\")) BETWEEN 5 AND 120");
                        });
                });

            modelBuilder.Entity("MesaSitec.Dominio.Entidades.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("MesaSitec.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId", "Rol", "Activo");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MesaSitec.Dominio.Entidades.Categoria", b =>
                {
                    b.HasOne("MesaSitec.Dominio.Entidades.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesaSitec.Dominio.Entidades.Solicitud", b =>
                {
                    b.HasOne("MesaSitec.Dominio.Entidades.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesaSitec.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AgenteId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MesaSitec.Dominio.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CategoriaId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MesaSitec.Dominio.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "SolicitanteId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MesaSitec.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("MesaSitec.Dominio.Entidades.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
