<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '@/services/api'
import { ApiError } from '@/lib/http'
import { useAuthStore } from '@/stores/auth'
import { useToastStore } from '@/stores/toast'
import { accionesPermitidas, puedeEditarSolicitud } from '@/domain/permisosSolicitud'
import type { Accion, SolicitudDetalle, UsuarioResumen } from '@/types/api'

const route=useRoute(), auth=useAuthStore(), toast=useToastStore()
const solicitud=ref<SolicitudDetalle>(), agentes=ref<UsuarioResumen[]>([]), cargando=ref(true), error=ref('')
const accion=ref<Accion>(), agenteId=ref(''), motivo=ref(''), modalError=ref(''), enviando=ref(false)
const id=String(route.params.id)
const esStaff=computed(()=>auth.usuario?.rol==='Admin'||auth.usuario?.rol==='Agente')
const puedeEditar=computed(()=>Boolean(solicitud.value&&auth.usuario&&puedeEditarSolicitud(solicitud.value.estado,auth.usuario.rol)))
const acciones=computed<Accion[]>(()=>solicitud.value&&auth.usuario?accionesPermitidas(solicitud.value.estado,auth.usuario.rol):[])
const requiereMotivo=computed(()=>accion.value==='resolver'||accion.value==='cancelar')
const etiquetas:Record<Accion,string>={asignar:'Asignar',iniciar:'Iniciar atención',resolver:'Resolver',cerrar:'Cerrar',reabrir:'Reabrir',cancelar:'Cancelar'}
function fecha(v:string|null){return v?new Intl.DateTimeFormat('es-GT',{dateStyle:'long',timeStyle:'short'}).format(new Date(v)):'—'}
async function cargar(){cargando.value=true;try{solicitud.value=await api.solicitud(id);if(esStaff.value)agentes.value=await api.agentes()}catch(e){error.value=e instanceof ApiError?e.message:'No fue posible cargar el detalle.'}finally{cargando.value=false}}
function abrir(a:Accion){accion.value=a;agenteId.value=solicitud.value?.agente?.id??'';motivo.value='';modalError.value=''}
function cerrarModal(){accion.value=undefined}
async function confirmar(){if(!accion.value)return;modalError.value='';if(accion.value==='asignar'&&!agenteId.value){modalError.value='Selecciona un agente.';return}const min=accion.value==='resolver'?20:10;if(requiereMotivo.value&&motivo.value.trim().length<min){modalError.value=`Escribe un motivo de al menos ${min} caracteres.`;return}enviando.value=true;try{solicitud.value=await api.transicionar(id,{accion:accion.value,agenteId:accion.value==='asignar'?agenteId.value:undefined,motivo:requiereMotivo.value?motivo.value.trim():undefined});toast.mostrar(`Acción “${etiquetas[accion.value]}” aplicada.`);cerrarModal()}catch(e){modalError.value=e instanceof ApiError?e.message:'No fue posible ejecutar la acción.'}finally{enviando.value=false}}
onMounted(cargar)
</script>

<template><main class="page"><p v-if="cargando" class="card loading">Cargando detalle…</p><p v-else-if="error" class="card error-box error">{{error}}</p><template v-else-if="solicitud"><div class="heading"><div><p data-testid="detalle-codigo">{{solicitud.codigo}}</p><h1 data-testid="detalle-titulo">{{solicitud.titulo}}</h1></div><RouterLink v-if="puedeEditar" class="btn" :to="`/solicitudes/${id}/editar`" data-testid="btn-editar">Editar</RouterLink></div><div class="layout"><article class="card main"><p class="description" data-testid="detalle-descripcion">{{solicitud.descripcion}}</p><dl><div><dt>Estado</dt><dd data-testid="detalle-estado"><span class="badge">{{solicitud.estado}}</span></dd></div><div><dt>Prioridad</dt><dd data-testid="detalle-prioridad">{{solicitud.prioridad}}</dd></div><div><dt>Categoría</dt><dd data-testid="detalle-categoria">{{solicitud.categoria.nombre}}</dd></div><div><dt>Agente</dt><dd data-testid="detalle-agente">{{solicitud.agente?.nombre??'Sin asignar'}}</dd></div><div><dt>Creada</dt><dd data-testid="detalle-fecha-creacion">{{fecha(solicitud.fechaCreacion)}}</dd></div><div><dt>Límite SLA</dt><dd data-testid="detalle-fecha-limite">{{fecha(solicitud.fechaLimiteSla)}}</dd></div><div v-if="solicitud.vencida"><dt>SLA</dt><dd class="error" data-testid="detalle-vencida">Vencida</dd></div><div v-if="solicitud.motivoResolucion||solicitud.motivoCancelacion"><dt>Motivo</dt><dd data-testid="detalle-motivo">{{solicitud.motivoResolucion??solicitud.motivoCancelacion}}</dd></div></dl></article><aside class="card actions"><h2>Acciones disponibles</h2><p v-if="acciones.length===0">No hay acciones disponibles para tu rol y este estado.</p><button v-for="a in acciones" :key="a" class="btn" :class="{'btn--danger':a==='cancelar'}" :data-testid="`btn-accion-${a}`" @click="abrir(a)">{{etiquetas[a]}}</button></aside></div></template>
<div v-if="accion" class="overlay" data-testid="modal-accion" @click.self="cerrarModal"><section class="card modal"><h2>{{etiquetas[accion]}}</h2><div v-if="accion==='asignar'" class="field"><label>Agente</label><select v-model="agenteId" data-testid="modal-select-agente"><option value="">Selecciona…</option><option v-for="a in agentes" :key="a.id" :value="a.id">{{a.nombre}}</option></select></div><div v-if="requiereMotivo" class="field"><label>Motivo</label><textarea v-model="motivo" data-testid="modal-motivo" rows="5" /></div><p v-if="modalError" class="error" data-testid="modal-error">{{modalError}}</p><div class="modal__buttons"><button class="btn btn--ghost dark" data-testid="modal-cancelar" @click="cerrarModal">Volver</button><button class="btn" data-testid="modal-confirmar" :disabled="enviando" @click="confirmar">{{enviando?'Procesando…':'Confirmar'}}</button></div></section></div></main></template>

<style scoped>.heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:1rem}.heading p{color:#61708a;font-weight:800}.heading p,.heading h1{margin:.2rem 0}.layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(15rem,1fr);gap:1rem}.description{font-size:1.05rem;line-height:1.7}.main dl{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.main dl div{padding:.8rem;border-radius:.6rem;background:#f6f8fb}.main dt{color:#61708a;font-size:.78rem;font-weight:800;text-transform:uppercase}.main dd{margin:.35rem 0 0}.actions{display:flex;flex-direction:column;align-items:stretch;gap:.7rem;height:max-content}.actions h2{margin-top:0}.overlay{position:fixed;z-index:30;inset:0;display:grid;padding:1rem;place-items:center;background:#0c1832aa}.modal{display:grid;gap:1rem;width:min(100%,30rem)}.modal h2{margin:0}.modal__buttons{display:flex;justify-content:flex-end;gap:.7rem}.dark{color:#25334a}@media(max-width:750px){.layout{grid-template-columns:1fr}.main dl{grid-template-columns:1fr}}</style>
