<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api } from '@/services/api'
import { ApiError } from '@/lib/http'
import type { Categoria, Estado, Pagina, Prioridad, SolicitudListado } from '@/types/api'

const estados:Estado[]=['Nueva','Asignada','EnProceso','Resuelta','Cerrada','Cancelada']
const prioridades:Prioridad[]=['Critica','Alta','Media','Baja']
const categorias=ref<Categoria[]>([]), pagina=ref<Pagina<SolicitudListado>>({items:[],page:1,pageSize:20,total:0,totalPaginas:0})
const filtros=reactive({estado:'',prioridad:'',categoriaId:'',vencidas:'',q:''})
const cargando=ref(true), error=ref(''); let temporizador:ReturnType<typeof setTimeout>|undefined

function params(){const p=new URLSearchParams({page:String(pagina.value.page),pageSize:'20',sort:'-fechaCreacion'});Object.entries(filtros).forEach(([k,v])=>{if(v)p.set(k==='categoriaId'?'categoriaId':k,v)});return p}
async function cargar(nuevaPagina=pagina.value.page){pagina.value.page=nuevaPagina;cargando.value=true;error.value='';try{pagina.value=await api.solicitudes(params())}catch(e){error.value=e instanceof ApiError?e.message:'No fue posible cargar las solicitudes.'}finally{cargando.value=false}}
function buscar(){if(temporizador)clearTimeout(temporizador);temporizador=setTimeout(()=>void cargar(1),350)}
function limpiar(){Object.assign(filtros,{estado:'',prioridad:'',categoriaId:'',vencidas:'',q:''});void cargar(1)}
function fecha(valor:string){return new Intl.DateTimeFormat('es-GT',{dateStyle:'medium',timeStyle:'short'}).format(new Date(valor))}
onMounted(async()=>{try{categorias.value=await api.categorias()}finally{await cargar(1)}})
</script>

<template><main class="page"><div class="heading"><div><p>Gestión de soporte</p><h1>Solicitudes</h1></div><RouterLink class="btn" to="/solicitudes/nueva" data-testid="btn-nueva-solicitud">Nueva solicitud</RouterLink></div>
<section class="card filters" aria-label="Filtros de solicitudes"><div class="field"><label for="filtro-estado">Estado</label><select id="filtro-estado" v-model="filtros.estado" data-testid="filtro-estado" @change="cargar(1)"><option value="">Todos</option><option v-for="e in estados" :key="e">{{e}}</option></select></div><div class="field"><label for="filtro-prioridad">Prioridad</label><select id="filtro-prioridad" v-model="filtros.prioridad" data-testid="filtro-prioridad" @change="cargar(1)"><option value="">Todas</option><option v-for="p in prioridades" :key="p">{{p}}</option></select></div><div class="field"><label for="filtro-categoria">Categoría</label><select id="filtro-categoria" v-model="filtros.categoriaId" data-testid="filtro-categoria" @change="cargar(1)"><option value="">Todas</option><option v-for="c in categorias" :key="c.id" :value="c.id">{{c.nombre}}</option></select></div><div class="field"><label for="filtro-vencidas">SLA</label><select id="filtro-vencidas" v-model="filtros.vencidas" data-testid="filtro-vencidas" @change="cargar(1)"><option value="">Todos</option><option value="true">Vencidas</option><option value="false">En plazo</option></select></div><div class="field search"><label for="filtro-busqueda">Buscar</label><input id="filtro-busqueda" v-model="filtros.q" data-testid="filtro-busqueda" placeholder="Código o título" @input="buscar"></div><button class="btn btn--ghost clean" data-testid="btn-limpiar-filtros" @click="limpiar">Limpiar</button></section>
<p v-if="cargando" class="card loading" data-testid="listado-cargando">Cargando solicitudes…</p><p v-else-if="error" class="card error-box error">{{error}}</p><p v-else-if="pagina.items.length===0" class="card empty" data-testid="listado-vacio">No hay solicitudes para estos filtros.</p>
<div v-else class="table-card"><table data-testid="tabla-solicitudes"><thead><tr><th>Código</th><th>Título</th><th>Estado</th><th>Prioridad</th><th>Categoría</th><th>SLA</th></tr></thead><tbody><tr v-for="s in pagina.items" :key="s.id" data-testid="fila-solicitud" :data-codigo="s.codigo"><td data-testid="celda-codigo"><RouterLink class="row-link" :to="`/solicitudes/${s.id}`"><strong>{{s.codigo}}</strong></RouterLink></td><td><RouterLink class="row-link" :to="`/solicitudes/${s.id}`">{{s.titulo}}</RouterLink></td><td data-testid="celda-estado"><span class="badge">{{s.estado}}</span></td><td data-testid="celda-prioridad">{{s.prioridad}}</td><td>{{s.categoria.nombre}}</td><td data-testid="celda-sla"><span v-if="s.vencida" class="badge overdue" data-testid="badge-vencida">Vencida</span><small>{{fecha(s.fechaLimiteSla)}}</small></td></tr></tbody></table></div>
<nav v-if="!cargando&&!error" class="pagination"><button class="btn btn--ghost dark" data-testid="paginacion-anterior" :disabled="pagina.page<=1" @click="cargar(pagina.page-1)">Anterior</button><span data-testid="paginacion-info">Página {{pagina.page}} de {{pagina.totalPaginas}} — {{pagina.total}} resultados</span><button class="btn btn--ghost dark" data-testid="paginacion-siguiente" :disabled="pagina.page>=pagina.totalPaginas" @click="cargar(pagina.page+1)">Siguiente</button></nav></main></template>

<style scoped>.heading{display:flex;align-items:center;justify-content:space-between;margin-bottom:1rem}.heading p,.heading h1{margin:.15rem 0}.filters{display:grid;grid-template-columns:repeat(4,1fr) 2fr auto;gap:.7rem;align-items:end;margin-bottom:1rem}.clean,.dark{color:#25334a}.table-card{overflow:auto;border:1px solid #dce4ef;border-radius:1rem;background:white}table{width:100%;border-collapse:collapse}th,td{padding:.85rem;text-align:left;border-bottom:1px solid #e5eaf2}th{color:#61708a;font-size:.78rem;text-transform:uppercase}tbody tr:hover{background:#f5f8fd}.row-link{display:block;color:#1f5fc7}.row-link:hover,.row-link:focus{text-decoration:underline}.overdue{margin-right:.4rem;background:#fee4e2;color:#b42318}td small{display:block;margin-top:.3rem}.pagination{display:flex;align-items:center;justify-content:center;gap:1rem;margin:1rem}@media(max-width:900px){.filters{grid-template-columns:repeat(2,1fr)}.search{grid-column:span 2}}@media(max-width:600px){.heading{align-items:flex-start;gap:1rem}.pagination{flex-wrap:wrap}.filters{grid-template-columns:1fr}.search{grid-column:auto}.clean{width:100%}}</style>
